name: Pipeline CI/CD

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GH_TOKEN:
        required: true
      GH_EMAIL:
        required: true
      ARGOCD_SERVER:
        required: true
      ARGOCD_USERNAME:
        required: true
      ARGOCD_PASSWORD:
        required: true
        
jobs:
  job1:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Management
        uses: actions/checkout@v6.0.2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set variables
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
      
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
  job2:
    name: Update Infra Repo and Deploy
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4
        with:
          repository: viniciusmorao-dev/infra-repo
          token: ${{ secrets.GH_TOKEN }}
          path: infra

      - name: Set variables
        run: |
          echo "APP_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Update deployment image
        run: |
          cd infra/template-apps/$APP_NAME

          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:$IMAGE_TAG|" deployment.yaml

      - name: Commit and push
        run: |
          cd infra

          git config user.name "viniciusmorao-dev"
          git config user.email "${{ secrets.GH_EMAIL }}"

          git add .
          git commit -m "Update $APP_NAME image to $IMAGE_TAG"
          git push
  # job3:
  #   name: Deploy ArgoCD
  #   runs-on: ubuntu-latest
  #   needs: job2
  #   steps:
  #     - name: Install ArgoCD CLI
  #       run: |
  #         curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
  #         chmod +x argocd
  #         sudo mv argocd /usr/local/bin/
      
  #     - name: Login ArgoCD
  #       run: |
  #         argocd login ${{ secrets.ARGOCD_SERVER }} \
  #           --username ${{ secrets.ARGOCD_USERNAME }} \
  #           --password ${{ secrets.ARGOCD_PASSWORD }} \
  #           --insecure
      
  #     - name: Sync App
  #       run: |
  #         sleep 10
  #         APP_NAME=${{ github.event.repository.name }}
  #         argocd app sync $APP_NAME
